services:
  nodejs-server:
    build:
      context: ./firebase.js
    ports:
      - "3080:3080"
    container_name: node-api
    volumes:
       - ./src/firebase.js
       - ./node_modules
  react-ui:
    build:
      context: ./app
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
       - ./src/app.js
       - ./node_modules
